import { logo0 } from "./imageParts/logo0.js";
import { logo1 } from "./imageParts/logo1.js";
import { logo2 } from "./imageParts/logo2.js";
import { headshot0 } from "./imageParts/headshot0.js";
import { headshot1 } from "./imageParts/headshot1.js";
import { headshot2 } from "./imageParts/headshot2.js";
import { headshot3 } from "./imageParts/headshot3.js";
import { headshot4 } from "./imageParts/headshot4.js";
import { headshot5 } from "./imageParts/headshot5.js";
import { headshot6 } from "./imageParts/headshot6.js";
import { headshot7 } from "./imageParts/headshot7.js";
import { headshot8 } from "./imageParts/headshot8.js";
import { headshot9 } from "./imageParts/headshot9.js";
import { headshot10 } from "./imageParts/headshot10.js";
import { headshot11 } from "./imageParts/headshot11.js";
import { headshot12 } from "./imageParts/headshot12.js";
import { headshot13 } from "./imageParts/headshot13.js";
import { headshot14 } from "./imageParts/headshot14.js";
import { headshot15 } from "./imageParts/headshot15.js";
import { headshot16 } from "./imageParts/headshot16.js";
import { headshot17 } from "./imageParts/headshot17.js";
import { brandPhoto0 } from "./imageParts/brandPhoto0.js";
import { brandPhoto1 } from "./imageParts/brandPhoto1.js";
import { brandPhoto2 } from "./imageParts/brandPhoto2.js";
import { brandPhoto3 } from "./imageParts/brandPhoto3.js";
import { brandPhoto4 } from "./imageParts/brandPhoto4.js";
import { brandPhoto5 } from "./imageParts/brandPhoto5.js";
import { brandPhoto6 } from "./imageParts/brandPhoto6.js";
import { brandPhoto7 } from "./imageParts/brandPhoto7.js";
import { brandPhoto8 } from "./imageParts/brandPhoto8.js";
import { brandPhoto9 } from "./imageParts/brandPhoto9.js";
import { brandPhoto10 } from "./imageParts/brandPhoto10.js";
import { brandPhoto11 } from "./imageParts/brandPhoto11.js";
import { brandPhoto12 } from "./imageParts/brandPhoto12.js";
import { brandPhoto13 } from "./imageParts/brandPhoto13.js";
import { brandPhoto14 } from "./imageParts/brandPhoto14.js";
import { brandPhoto15 } from "./imageParts/brandPhoto15.js";
import { brandPhoto16 } from "./imageParts/brandPhoto16.js";
import { brandPhoto17 } from "./imageParts/brandPhoto17.js";
import { brandPhoto18 } from "./imageParts/brandPhoto18.js";
import { brandPhoto19 } from "./imageParts/brandPhoto19.js";
import { brandPhoto20 } from "./imageParts/brandPhoto20.js";

export const logoData = [logo0, logo1, logo2].join("");
export const headshotData = [headshot0, headshot1, headshot2, headshot3, headshot4, headshot5, headshot6, headshot7, headshot8, headshot9, headshot10, headshot11, headshot12, headshot13, headshot14, headshot15, headshot16, headshot17].join("");
export const brandPhotoData = [brandPhoto0, brandPhoto1, brandPhoto2, brandPhoto3, brandPhoto4, brandPhoto5, brandPhoto6, brandPhoto7, brandPhoto8, brandPhoto9, brandPhoto10, brandPhoto11, brandPhoto12, brandPhoto13, brandPhoto14, brandPhoto15, brandPhoto16, brandPhoto17, brandPhoto18, brandPhoto19, brandPhoto20].join("");
